# Generated by Django 5.1.1 on 2024-11-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0002_mailing_user_mailingrecipient_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_manage_mailing", "Может управлять рассылками")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
